### ISSUE TITLE
No consensus appears to be reached

### ISSUE THREAD

**Issue by masterloser** [antitree/private-tor-network#14]
Building using the 'quickstart' instructions on Debian 8, Debian 9 and Ubuntu, I run into the same issue where consensus doesn't seem to happen. Can connect to the sock proxy, all containers come up, tor directory is consistent across containers.
Cannot connect to hidden service. arm does not show consensus.

**Comment by antitree** [comment]
I've found this to happen sometimes. How long of a period have you waited for consensus and which versions of tor did you use? I'd try to flush any persistent volumes you're using if possible.
